/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HelpSupportRouteImport } from './routes/help-support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDrilldownRouteImport } from './routes/_authenticated/drilldown'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedHousesRouteImport } from './routes/_authenticated/houses'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMasterAdminRouteImport } from './routes/_authenticated/master-admin'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedAssessmentsMemberIdRouteImport } from './routes/_authenticated/assessments.$memberId'
import { Route as AuthenticatedHousesHouseIdRouteImport } from './routes/_authenticated/houses.$houseId'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'
import { Route as AuthenticatedSurveyNewRouteImport } from './routes/_authenticated/survey.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrilldownRoute = AuthenticatedDrilldownRouteImport.update({
  id: '/drilldown',
  path: '/drilldown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHousesRoute = AuthenticatedHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterAdminRoute =
  AuthenticatedMasterAdminRouteImport.update({
    id: '/master-admin',
    path: '/master-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsMemberIdRoute =
  AuthenticatedAssessmentsMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedHousesHouseIdRoute =
  AuthenticatedHousesHouseIdRouteImport.update({
    id: '/$houseId',
    path: '/$houseId',
    getParentRoute: () => AuthenticatedHousesRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSurveyNewRoute = AuthenticatedSurveyNewRouteImport.update({
  id: '/survey/new',
  path: '/survey/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/help-support': typeof HelpSupportRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drilldown': typeof AuthenticatedDrilldownRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/houses': typeof AuthenticatedHousesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/map': typeof AuthenticatedMapRoute
  '/master-admin': typeof AuthenticatedMasterAdminRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assessments/$memberId': typeof AuthenticatedAssessmentsMemberIdRoute
  '/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/survey/new': typeof AuthenticatedSurveyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/help-support': typeof HelpSupportRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drilldown': typeof AuthenticatedDrilldownRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/houses': typeof AuthenticatedHousesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/map': typeof AuthenticatedMapRoute
  '/master-admin': typeof AuthenticatedMasterAdminRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assessments/$memberId': typeof AuthenticatedAssessmentsMemberIdRoute
  '/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/survey/new': typeof AuthenticatedSurveyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/help-support': typeof HelpSupportRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drilldown': typeof AuthenticatedDrilldownRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/houses': typeof AuthenticatedHousesRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/master-admin': typeof AuthenticatedMasterAdminRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/assessments/$memberId': typeof AuthenticatedAssessmentsMemberIdRoute
  '/_authenticated/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/survey/new': typeof AuthenticatedSurveyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/faq'
    | '/features'
    | '/help-support'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/analytics'
    | '/assessments'
    | '/dashboard'
    | '/drilldown'
    | '/followups'
    | '/houses'
    | '/import'
    | '/map'
    | '/master-admin'
    | '/notifications'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/team'
    | '/users'
    | '/assessments/$memberId'
    | '/houses/$houseId'
    | '/members/$memberId'
    | '/survey/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/faq'
    | '/features'
    | '/help-support'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/analytics'
    | '/assessments'
    | '/dashboard'
    | '/drilldown'
    | '/followups'
    | '/houses'
    | '/import'
    | '/map'
    | '/master-admin'
    | '/notifications'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/team'
    | '/users'
    | '/assessments/$memberId'
    | '/houses/$houseId'
    | '/members/$memberId'
    | '/survey/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/download'
    | '/faq'
    | '/features'
    | '/help-support'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activity'
    | '/_authenticated/analytics'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/drilldown'
    | '/_authenticated/followups'
    | '/_authenticated/houses'
    | '/_authenticated/import'
    | '/_authenticated/map'
    | '/_authenticated/master-admin'
    | '/_authenticated/notifications'
    | '/_authenticated/quality'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/users'
    | '/_authenticated/assessments/$memberId'
    | '/_authenticated/houses/$houseId'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/survey/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpSupportRoute: typeof HelpSupportRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-support': {
      id: '/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drilldown': {
      id: '/_authenticated/drilldown'
      path: '/drilldown'
      fullPath: '/drilldown'
      preLoaderRoute: typeof AuthenticatedDrilldownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses': {
      id: '/_authenticated/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof AuthenticatedHousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-admin': {
      id: '/_authenticated/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof AuthenticatedMasterAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$memberId': {
      id: '/_authenticated/assessments/$memberId'
      path: '/$memberId'
      fullPath: '/assessments/$memberId'
      preLoaderRoute: typeof AuthenticatedAssessmentsMemberIdRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/houses/$houseId': {
      id: '/_authenticated/houses/$houseId'
      path: '/$houseId'
      fullPath: '/houses/$houseId'
      preLoaderRoute: typeof AuthenticatedHousesHouseIdRouteImport
      parentRoute: typeof AuthenticatedHousesRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/survey/new': {
      id: '/_authenticated/survey/new'
      path: '/survey/new'
      fullPath: '/survey/new'
      preLoaderRoute: typeof AuthenticatedSurveyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAssessmentsRouteChildren {
  AuthenticatedAssessmentsMemberIdRoute: typeof AuthenticatedAssessmentsMemberIdRoute
}

const AuthenticatedAssessmentsRouteChildren: AuthenticatedAssessmentsRouteChildren =
  {
    AuthenticatedAssessmentsMemberIdRoute:
      AuthenticatedAssessmentsMemberIdRoute,
  }

const AuthenticatedAssessmentsRouteWithChildren =
  AuthenticatedAssessmentsRoute._addFileChildren(
    AuthenticatedAssessmentsRouteChildren,
  )

interface AuthenticatedHousesRouteChildren {
  AuthenticatedHousesHouseIdRoute: typeof AuthenticatedHousesHouseIdRoute
}

const AuthenticatedHousesRouteChildren: AuthenticatedHousesRouteChildren = {
  AuthenticatedHousesHouseIdRoute: AuthenticatedHousesHouseIdRoute,
}

const AuthenticatedHousesRouteWithChildren =
  AuthenticatedHousesRoute._addFileChildren(AuthenticatedHousesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDrilldownRoute: typeof AuthenticatedDrilldownRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedHousesRoute: typeof AuthenticatedHousesRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMasterAdminRoute: typeof AuthenticatedMasterAdminRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedSurveyNewRoute: typeof AuthenticatedSurveyNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDrilldownRoute: AuthenticatedDrilldownRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedHousesRoute: AuthenticatedHousesRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMasterAdminRoute: AuthenticatedMasterAdminRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedSurveyNewRoute: AuthenticatedSurveyNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HelpSupportRoute: HelpSupportRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
