/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedHousesRouteImport } from './routes/_authenticated/houses'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHousesHouseIdRouteImport } from './routes/_authenticated/houses.$houseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHousesRoute = AuthenticatedHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHousesHouseIdRoute =
  AuthenticatedHousesHouseIdRouteImport.update({
    id: '/$houseId',
    path: '/$houseId',
    getParentRoute: () => AuthenticatedHousesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/houses': typeof AuthenticatedHousesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/map': typeof AuthenticatedMapRoute
  '/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/houses': typeof AuthenticatedHousesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/map': typeof AuthenticatedMapRoute
  '/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/houses': typeof AuthenticatedHousesRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/houses/$houseId': typeof AuthenticatedHousesHouseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/followups'
    | '/houses'
    | '/import'
    | '/map'
    | '/houses/$houseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/followups'
    | '/houses'
    | '/import'
    | '/map'
    | '/houses/$houseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/followups'
    | '/_authenticated/houses'
    | '/_authenticated/import'
    | '/_authenticated/map'
    | '/_authenticated/houses/$houseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses': {
      id: '/_authenticated/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof AuthenticatedHousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/$houseId': {
      id: '/_authenticated/houses/$houseId'
      path: '/$houseId'
      fullPath: '/houses/$houseId'
      preLoaderRoute: typeof AuthenticatedHousesHouseIdRouteImport
      parentRoute: typeof AuthenticatedHousesRoute
    }
  }
}

interface AuthenticatedHousesRouteChildren {
  AuthenticatedHousesHouseIdRoute: typeof AuthenticatedHousesHouseIdRoute
}

const AuthenticatedHousesRouteChildren: AuthenticatedHousesRouteChildren = {
  AuthenticatedHousesHouseIdRoute: AuthenticatedHousesHouseIdRoute,
}

const AuthenticatedHousesRouteWithChildren =
  AuthenticatedHousesRoute._addFileChildren(AuthenticatedHousesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedHousesRoute: typeof AuthenticatedHousesRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedHousesRoute: AuthenticatedHousesRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
